Table factHigherLevelReview{
 DateReceivedKey integer
 DateClosedKey integer
 DatePriorDecisionDateKey integer
 VeteranKey integer
 IssueCategoryKey integer
 BenefitTypeKey integer
 IssueDescriptionKey integer
 ClosedStatusKey integer
 IssueCount integer
 TotalCompletionDays integer
 TotalWaitingDays integer
 HLReviewId varchar
}

Table dimDate{
  DateKey integer [primary key]
  DateName varchar
  DayofWeekNumber smallint
  DayName varchar
  DayofMonth smallint
  DayofYear integer
  WeekNumber smallint
  MonthName varchar
  MonthNumber smallint
  CalendarQuarter smallint
  CalendarYear integer
  FiscalYear varchar
  DayofWeekCategory varchar
  ShortMonthName varchar
  IsLastDayofMonth varchar
  CalendarYearMonth varchar
}

Table dimVeteran {
  VeteranKey integer [primary key]
  FirstName varchar
  LastName varchar
  FileNumber varchar
  MiddleName varchar
  BirthDate date
}

Table dimBenefitType{
  BenefitTypeKey integer [primary key]
  BenefitType varchar(20)
}
Table dimIssueDescription{
  IssueDescriptionKey integer [primary key]
  IssueDescription varchar(255)
}
Table dimClosedStatus{
  ClosedStatuskey integer [primary key]
  ClosedStatusName varchar(50)
}
Table dimIssueCategory{
  IssueCategoryKey integer [primary key]
  IssueCategoryDescription varchar(255)
}

Ref: "dimDate"."DateKey" < "factHigherLevelReview"."DateReceivedKey"

Ref: "dimDate"."DateKey" < "factHigherLevelReview"."DateClosedKey"

Ref: "dimDate"."DateKey" < "factHigherLevelReview"."DatePriorDecisionDateKey"

Ref: "dimVeteran"."VeteranKey" < "factHigherLevelReview"."VeteranKey"

Ref: "dimClosedStatus"."ClosedStatuskey" < "factHigherLevelReview"."ClosedStatusKey"

Ref: "dimIssueCategory"."IssueCategoryKey" < "factHigherLevelReview"."IssueCategoryKey"

Ref: "dimIssueDescription"."IssueDescriptionKey" < "factHigherLevelReview"."IssueDescriptionKey"

Ref: "dimBenefitType"."BenefitTypeKey" < "factHigherLevelReview"."BenefitTypeKey"
